### ISSUE TITLE
Task for custom charset

### ISSUE THREAD

**Issue by wheelq** [hashview/hashview#206]
I would like to use the custom charset [a-z][A-Z][0-9] with the length between 4 and 9. but the current task support mask and bruteforce without the charsets. How do I create such task?

**Comment by ccammilleri** [comment]
@wheelq I'll apologize in advance since this is a hack until we add more hashcat options to hashview. Simply add your custom charset to the mask field on the create new task page. Then, define your length after it. Rinse and repeat by creating multiple tasks from 4 to 9 in length.

![hashview-mask](https://cloud.githubusercontent.com/assets/1406479/23027898/5ee2aeda-f42b-11e6-8d32-86b1c3eb0bd4.png)

**Comment by ccammilleri** [comment]
closing for now. @wheelq lmk if this doesnt work. long term we'll be adding additional hashcat commands
