### ISSUE TITLE
How to run 2 jobs simultaneously ?

### ISSUE THREAD

**Issue by totoPouet** [hashview/hashview#274]
Hi,
First thanks for your great job with this front end ! :)

I would like to know if it was possible to get 2 jobs running in the same time on the same host ? And how to do this.

Thanks,

**Comment by ccammilleri** [comment]
Sorry, but this isn't supported yet. 

This presents some odd challenges that might make it better to just isolate tasks per card. We'll reopen the discussion when we approach implementation.

**Comment by jarhat** [comment]
Hello,

I'm also interested in this..

My idea for a workaround is to simply hard-code the --session parameter in helpers/build_crack_cmd.rb.
Now, one would only have make sure tasks get started immediately, spawning a new hashcat instance, instead of the task being queued.

I don't know whether this is easy to do.. would be great to hear if it can be done easily.
