### ISSUE TITLE
db:reset doesn't work to reset DB on latest build

### ISSUE THREAD

**Issue by ama21n** [hashview/hashview#302]
Is there an alternative to getting this working? Without it I have multiple "Acme Corp" entries I can't seem to remove. Note: This worked on a previous build on Ubuntu 14.04 (im now on 16.04).

# RACK_ENV=production rake db:reset
rake aborted!
Don't know how to build task 'db:reset' (see --tasks)
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

# RACK_ENV=production rake db:reset --trace
rake aborted!
Don't know how to build task 'db:reset' (see --tasks)
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/task_manager.rb:58:in `[]'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:151:in `invoke_task'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.2/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.2.2/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

# RACK_ENV=production rake --tasks
rake db:migrate            # Migrate From old DB to new DB schema
rake db:provision_agent    # Setup local agent
rake db:setup              # create, setup schema, and load defaults into db
rake db:upgrade            # Upgrade your instance of HashView / Perform non destructive auto migration
rake resque:failures:sort  # Sort the 'failed' queue for the redis_multi_queue failure backend
rake resque:scheduler      # Start Resque Scheduler
rake resque:setup          # Resque scheduler setup
rake resque:work           # Start a Resque worker
rake resque:workers        # Start multiple Resque workers
rake test                  # Run tests

**Comment by i128** [comment]
You should be able to remove the multiple acme company entries via the
customer menu in the upper right hand side.

Though it doesn't address why DB:reset is failing the above should fix your
initial issue

On May 26, 2017 1:17 AM, "ama21n" <notifications@github.com> wrote:

Is there an alternative to getting this working? Without it I have multiple
"Acme Corp" entries I can't seem to remove. Note: This worked on a previous
build on Ubuntu 14.04 (im now on 16.04).
RACK_ENV=production rake db:reset

rake aborted!
Don't know how to build task 'db:reset' (see --tasks)
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/exe/rake:27:in <top
(required)>' /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in
eval'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `
'
(See full trace by running task with --trace)

RACK_ENV=production rake db:reset --trace

rake aborted!
Don't know how to build task 'db:reset' (see --tasks)
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/task_manager.rb:58:in
[]' /usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/
application.rb:151:ininvoke_task'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:108:in
block (2 levels) in top_level' /usr/local/rvm/gems/ruby-2.2.
2/gems/rake-12.0.0/lib/rake/application.rb:108:ineach'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:108:in
block in top_level' /usr/local/rvm/gems/ruby-2.2.
2/gems/rake-12.0.0/lib/rake/application.rb:117:inrun_with_threads'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:102:in
top_level' /usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/
application.rb:80:inblock in run'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/lib/rake/application.rb:178:in
standard_exception_handling' /usr/local/rvm/gems/ruby-2.2.
2/gems/rake-12.0.0/lib/rake/application.rb:77:inrun'
/usr/local/rvm/gems/ruby-2.2.2/gems/rake-12.0.0/exe/rake:27:in <top
(required)>' /usr/local/rvm/gems/ruby-2.2.2/bin/rake:23:inload'
/usr/local/rvm/gems/ruby-2.2.2/bin/rake:23:in <main>'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:ineval'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `
'

RACK_ENV=production rake --tasks

rake db:migrate # Migrate From old DB to new DB schema
rake db:provision_agent # Setup local agent
rake db:setup # create, setup schema, and load defaults into db
rake db:upgrade # Upgrade your instance of HashView / Perform non
destructive auto migration
rake resque:failures:sort # Sort the 'failed' queue for the
redis_multi_queue failure backend
rake resque:scheduler # Start Resque Scheduler
rake resque:setup # Resque scheduler setup
rake resque:work # Start a Resque worker
rake resque:workers # Start multiple Resque workers
rake test # Run tests

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hashview/hashview/issues/302>, or mute the thread

**Comment by i128** [comment]
Committing, Good job!
