### ISSUE TITLE
DataMapper Performance (AKA - blame DataMapper, then convert to Sequel)

### ISSUE THREAD

**Issue by nicbrink** [hashview/hashview#321]
Ok, lets see if I can explain this.
I have a file with ~3.4M hashes.  When I try to import it into hashview it takes a crazy long amount of time.  Hashview basically becomes unusable due to the time to create the hashfile for hashcat.  I am curious if others have experienced the same with extremely large hash files.  

So, I did some work to on importing both 10K and 100K of NTLM hashes with no username and here are my results.
10K - 44.5 Seconds
100K - 412.73 Seconds

Reading up on the subject I tried a few things to improve performance.  
1.  Attempted to create additional processes to add hashes to the database using the fork command.  This had about a 20% improvement in the time it took, however, I dont think this is a good solution.  
2.  Next I tried to use multi-threading, but it turns out that does not work well with ruby due to Global Interpreter Lock.
3. Evaluated DataMapper against ActiveRecord and Sequel.  It turns out Sequel does provide a pretty significant performance boost.

Using Sequel to import a 10K and 100K worth of NTLM hashes with no username resulted in:
10K - 8.22 Seconds
100K - 97.67 Seconds

Here is the link to the branch I created to do testing with.
https://github.com/nicbrink/hashview/tree/sequel

I am curious everyones thoughts on this regarding performance.  Are my results of DataMapper vs Sequel atypical?

Thanks again!

**Comment by i128** [comment]
1) great work!
2) we've noticed similar performances issues at those large number of
hashes. I will take a look at the performance enhancements incurred by
using Sequel. Unfortunately it might a few weeks with work and other
scheduling conflicts. One major issue during import is that we're indexing
each hash to aid in future queries. This introduces upfront costs during
import.  A few ideas we've been kicking around has been to 1) improve
processes where possible, 2) split hashes table into multiple tables by
hash type, 3 switch from datamapper.

Thanks again for taking the time to perform the tests mentioned. I'd like
to investigate this further.

**Comment by ccammilleri** [comment]
my 2 cents...

if we had to do it again we would have gone with sequel. I dont think datamapper is active nor does the developer even suggest using it anymore. the switch would suck, but better to do it sooner rather than later. we are still ALPHA ;-)  I'd think for the short term making hash importing a background job would be best, but this comes with some issues too.

Thanks for testing this. its great to get real data on this issue, but I am surprised that there is that much performance difference between the two...

**Comment by nicbrink** [comment]
Wow, quick response!  I am willing to help with the transition if that is what you guys decide.  Making the one test change seemed pretty straight forward.  I am anxious to see if you see similar performance improvements.    I think there may be some other areas where we could eek out an improvement such as sequels ability to do a batch insert.

**Comment by nicbrink** [comment]
So I did some more work, focusing on the hashimporter.rb functions.  I created new functions using sequel and performing bulk inserts.  From what I can tell I replicated all the original functionality, but did not test every code path.  
Using this code when executed with the development environment variable(IE original datamapper code) I was able to upload 100K NTLM Hashes in 404.30 seconds.
Setting the environment variable to test(IE sequel code) I was able to upload 100K hashes in 5.72 seconds!!!!!!

Now the one thing I will say is that on my development VM which only has 2G ram and 2G swap space, if I try to insert more then 300K records, I will run out of memory and crash the database with the new code. I doubt this is a big deal, but it may cause issues in the future.

If someone could take a look at my code and confirm that I took everything into account, that would be awesome.  I want to move on and maybe look for some efficiencies else where.

**Comment by i128** [comment]
Woah that's awesome. Is the DB / table indexed? I know that's part of our
current slowdown with mysql

On Aug 12, 2017 10:29 AM, "nicbrink" <notifications@github.com> wrote:

So I did some more work, focusing on the hashimporter.rb functions. I
created new functions using sequel and performing bulk inserts. From what I
can tell I replicated all the original functionality, but did not test
every code path.
Using this code when executed with the development environment variable(IE
original datamapper code) I was able to upload 100K NTLM Hashes in 404.30
seconds.
Setting the environment variable to test(IE sequel code) I was able to
upload 100K hashes in 5.72 seconds!!!!!!

Now the one thing I will say is that on my development VM which only has 2G
ram and 2G swap space, if I try to insert more then 300K records, I will
run out of memory and crash the database with the new code. I doubt this is
a big deal, but it may cause issues in the future.

If someone could take a look at my code and confirm that I took everything
into account, that would be awesome. I want to move on and maybe look for
some efficiencies else where.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/hashview/hashview/issues/321#issuecomment-321988114>,
or mute the thread

**Comment by nicbrink** [comment]
I didnt make any changes to the database itself.  Here is how mine currently looks.

mysql> show index from hashes\G
*************************** 1. row ***************************
        Table: hashes
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 185369
     Sub_part: NULL
       Packed: NULL
         Null:
   Index_type: BTREE
      Comment:
Index_comment:
*************************** 2. row ***************************
        Table: hashes
   Non_unique: 0
     Key_name: index_of_orignalhashes
 Seq_in_index: 1
  Column_name: originalhash
    Collation: A
  Cardinality: 185884
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment:
Index_comment:
*************************** 3. row ***************************
        Table: hashes
   Non_unique: 1
     Key_name: index_of_hashtypes
 Seq_in_index: 1
  Column_name: hashtype
    Collation: A
  Cardinality: 2
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment:
Index_comment:
3 rows in set (0.00 sec)

mysql> show index from hashfilehashes\G
*************************** 1. row ***************************
        Table: hashfilehashes
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 200096
     Sub_part: NULL
       Packed: NULL
         Null:
   Index_type: BTREE
      Comment:
Index_comment:
*************************** 2. row ***************************
        Table: hashfilehashes
   Non_unique: 1
     Key_name: index_hashfilehashes_hash_id
 Seq_in_index: 1
  Column_name: hash_id
    Collation: A
  Cardinality: 200096
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment:
Index_comment:
*************************** 3. row ***************************
        Table: hashfilehashes
   Non_unique: 1
     Key_name: index_hashfilehashes_hashfile_id
 Seq_in_index: 1
  Column_name: hashfile_id
    Collation: A
  Cardinality: 1
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment:
Index_comment:
3 rows in set (0.00 sec)

**Comment by nicbrink** [comment]
Take a look at the branch I created.
https://github.com/nicbrink/hashview/tree/sequel_upgrade
I have updated hashview to use the sequel plugin instead of the datamapper plugin.  I think I was worked out all the bugs, but the changes required where subtle so it may not be perfect yet.  

I have only done some performance tuning on the hashimporter part, but even just a straight conversion has led to a slight performance gain from what I can tell.  

Let me know what you think

**Comment by i128** [comment]
This has been implemented into the master branch. While performance has improved overall, I think there are opportunities to make it even better. For example, in your branch you used bulk imports meaning 10+ hashes at a time.  The problem with this approach is that there are situation where imported hashes already exist. Normally we'd just ignore this, but we ran into problems where users were accidentally uploading hashes and assigning them the wrong hash type. So the solution was to update hashes that were duplicates during uploads, and just change the hash type to match the newest value...i.e. trust that the most recent upload of a hashfile has the correct hash type. 

However, this is not a perfect solution as what happens if the previously imported hash had the right hash type, was cracked, and now a user uploads a new file with matching hashes... we dont want to overwrite or change the known good hash:pass value. So in these instances, we ignore the update on a per hash basis.

As you can see... doing it straight bulk import means we side step these checks so we had to revert back to single line imports. The good news is that it did improve speeds overall, but maybe not as good as we'd like.
